synapz/WebApp/mcq-latest/mcq/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *

from mcqportal import views


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',

	 url(r'^$', views.index, name='index'),
	  # Login / logout.
#    (r'^login/$', 'django.contrib.auth.views.login'),
#    (r'^logout/$', logout_page),

    # Examples:
    # url(r'^$', 'mcq.views.home', name='home'),
    # url(r'^mcq/', include('mcq.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	url(r'^mcqportal/', include('mcqportal.urls', namespace="mcqportal")),

  # Serve static content.
 #   (r'^static/(?P<path>.*)$', 'django.views.static.serve',
  #      {'document_root': 'static'}),

)

synapz/WebApp/mcq-latest/mcqportal/urls.py
from django.conf.urls import patterns, url

from mcqportal import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
#	url(r'^p1_submit/$', views.p1_submit, name='index'),
	url(r'^pg1$', views.chksession, name='pg1'),
    url(r'^pg2$', views.chksession, name='pg2'),
	url(r'^pg3$', views.chksession, name='pg3'),
	url(r'^pg4$', views.chksession, name='pg4'),
	url(r'^pg5$', views.pg5, name='pg5'),
	url(r'^login', views.login, name='login'),
	url(r'^signin$', views.signin, name='signin'),
	url(r'^signup$', views.signup, name='signup'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^fbsave', views.save, name='save'),
)

synapz/WebApp/mcq-latest/mcqportal/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class Questiondetails(models.Model):
    id = models.IntegerField(primary_key=True)
    question = models.CharField(max_length=900L, db_column='Question', blank=True) # Field name made lowercase.
    optiona = models.CharField(max_length=255L, blank=True)
    optionb = models.CharField(max_length=255L, blank=True)
    optionc = models.CharField(max_length=255L, blank=True)
    optiond = models.CharField(max_length=255L, blank=True)
    answer = models.CharField(max_length=1L, blank=True)
    category = models.CharField(max_length=255L, blank=True)
    class Meta:
        db_table = 'QuestionDetails'
    def __unicode__(self):
	return self.question


class Members(models.Model):
    memberid = models.IntegerField(primary_key=True, db_column='Memberid') # Field name made lowercase.
    username = models.CharField(max_length=255L, db_column='Username') # Field name made lowercase.
    email = models.CharField(max_length=255L, db_column='Email') # Field name made lowercase.
    password = models.CharField(max_length=255L, db_column='Password') # Field name made lowercase.
    activation = models.CharField(max_length=40L, db_column='Activation', blank=True) # Field name made lowercase.
    gradyear = models.IntegerField(null=True, db_column='gradYear', blank=True) # Field name made lowercase.
    mobile = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=255L, blank=True)
    class Meta:
        db_table = 'members'
    def __unicode__(self):
	    return self.username

class answers(models.Model):
    memberid = models.IntegerField(db_column='Memberid') # Field name made lowercase.
    qid = models.ForeignKey('Questiondetails')
    answer = models.CharField(max_length=1L, blank=True)
    def __unicode__(self):
        return self.answer

synapz/WebApp/mcq-latest/mcqportal/views.py
from django.http import HttpResponse
from django.template import Context, loader
from django.http import Http404,HttpResponseRedirect, HttpResponse
from mcqportal.models import Questiondetails,Members,answers
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404,render
import random 
import copy
from django.db.models import Count
from django.db.models import Max

def index(request):
	request.session['counter'] = copy.deepcopy([])
	request.session['mcq'] = copy.deepcopy([[],[],[],[]])
	if 'uid' in request.session :
#		name=request.session['name']	
#		return HttpResponse(name);
		request.session['pg1session']=1
		if 'pg2session' in request.session:
			del request.session['pg2session']
		if 'pg3session' in request.session:
			del request.session['pg3session']
		if 'pg4session' in request.session:
			del request.session['pg4session']
		return render(request,'mcqportal/index.html', {'user':request.session['name']})
	else:
		return render(request,'mcqportal/login.html')
#	return render(request,'mcqportal/index.html')


"""def p1_submit(request):
#	return HttpResponse("sjkdjhasdlfhladsfl")	
    try:
        mcq1 = list(Questiondetails.objects.all())
        random.shuffle(mcq1)
        mcq = mcq1[:15]
    except Questiondetails.DoesNotExist:
        raise Http404
    return render(request,'mcqportal/pg1.html',{'mcq':mcq})"""

def login(request):	
	return render(request,'mcqportal/login.html')

def signin(request):
	try:
		m = Members.objects.get(email=request.POST['eid_signIn'])
	except Members.DoesNotExist:
		context = {
			'alerts': "invalid Email: u may SIGNUP",  
			'class': "error"
		}
		return render(request,'mcqportal/login.html', context)
	if m.password == request.POST['passwd_signIn']:
		request.session['uid'] = m.memberid
		request.session['name'] = m.username
		return render(request,'mcqportal/index.html')
	#	return HttpResponse("You're logged in.")
   	else:
		context = {
			'alerts': "Email and password did not match. Please try again.",  
			'class': "error"
		}
		return render(request,'mcqportal/login.html', context)
	
		#return HttpResponse("Your username and password didn't match.")
#	return HttpResponse("Successfully logged in");

def signup(request):
	name=request.POST['name']
	email=request.POST['eid']
	password=request.POST['passwd']
	try:
		m = Members.objects.get(email=email)
		context = {
			'alerts': "Email already exists.",  
			'class': "error"
		}
		return render(request,'mcqportal/login.html', context)
	except Members.DoesNotExist:
		count = Members.objects.all().count()
		if count == 0:
			memid = 1
		else:
			memid = Members.objects.order_by("-memberid")[0].memberid + 1
		user=Members(memberid=memid,username=name,email=email,password=password)
		user.save()
		request.session['uid']=user.memberid
		request.session['name'] = user.username
#	return HttpResponse(name + "   "  + email + "    " + password);
		return index(request)


def chksession(request):
	if 'page' in request.POST:
		if request.POST['page']=='pg1':
			del request.session['pg1session']
			request.session['pg2session']=1
		if request.POST['page']=='pg2':
			del request.session['pg2session']
			request.session['pg3session']=1
		if request.POST['page']=='pg3':
			del request.session['pg3session']
			request.session['pg4session']=1
		if request.POST['page']=='pg4':
			del request.session['pg4session']
	
	if 'pg1session' in request.session:
		return pg1(request)
	if 'pg2session' in request.session:
		return pg2(request)
	if 'pg3session' in request.session:
		return pg3(request)
	if 'pg4session' in request.session:
		return pg4(request)
	return pg5(request)



def logout(request):
    del request.session
    return render(request,'mcqportal/login.html')

def pg1(request):
    if 'uid' not in request.session:
        return render(request,'mcqportal/login.html')
    if  'pg1session' not in request.session:
	return chksession(request)

#    if request.session['pg1session']==0:
 #       return render(request,'mcqportal/index.html')
    uid=request.session['uid']
    try:
        a = list(Questiondetails.objects.filter(category=1))
        random.shuffle(a)
        mcq = a[:1]
        for i in mcq:
            v=Questiondetails.objects.get(id=i.id)
            b=answers(memberid=uid,qid=v,answer=0)
            b.save()
#        request.session['pg1session']=0;
#     request.session['mcq'][0] = copy.deepcopy(a[:1])
    except Questiondetails.DoesNotExist:
        raise Http404
    return render(request,'mcqportal/pg1.html',{'mcq':mcq,'user':request.session['name']})
  #  return render(request,'mcqportal/pg1.html',{'mcq':request.session['mcq'][0], 'b':"Aptitude"})


"""        try:
            a=answers(memberid=uid,qid=i,answer=request.POST[i])
            a.save()	"""

def pg2(request):
    if 'uid' not in request.session :
        return render(request,'mcqportal/login.html')
    if  'pg2session' not in request.session:
	return chksession(request)

#    global ans1
#	myanswers=""
    uid=request.session['uid']
    for i in request.POST:
        #		myanswers+="qid-"
#		myanswers+=i
#		myanswers+="the answer-"
#		myanswers+=request.POST[i]

#        except:
         try:
             a=answers.objects.filter(qid=i).aggregate(Max('id'))
	     b=answers.objects.get(id=a['id__max'])
             b.answer = request.POST[i]
             b.save()
         except:
             apple=""
#    for i in request.session['mcq'][0]:
#        if str(i.pk) in request.POST:
#            if i.answer == request.POST[str(i.pk)]:
#                count = count + 1
#            ans1.append(request.POST[str(i.pk)])
#        else:
#            ans1.append(0)
#    lis = request.session['counter']
#    lis.append(count)
#    request.session['counter'] = copy.deepcopy(lis)
    #return HttpResponse( request.session['mcq'][0])
#  return render(request,'mcqportal/pg2.html',{'mcq':request.session['mcq'][1], 'b':"Programming"})
#   return render(request,'mcqportal/pg2.html')
    try:
        c = list(Questiondetails.objects.filter(category=2))
        random.shuffle(c)
        mcq = c[:1]
        for i in mcq:
            v=Questiondetails.objects.get(id=i.id)
            b=answers(memberid=uid,qid=v,answer=0)
            b.save()	
#     request.session['mcq'][0] = copy.deepcopy(a[:1])
    except Questiondetails.DoesNotExist:
        raise Http404
	
#	return HttpResponse(myanswers)
    return render(request,'mcqportal/pg2.html',{'mcq':mcq,'user':request.session['name']})

def pg3(request):

    #uid=request.session['uid']
    if 'uid' not in request.session :
        return render(request,'mcqportal/login.html')
    if  'pg3session' not in request.session:
	return chksession(request)

    uid=request.session['uid']
    for i in request.POST:
        #		myanswers+="qid-"
#		myanswers+=i
#		myanswers+="the answer-"
#		myanswers+=request.POST[i]
         try:
	     a=answers.objects.filter(qid=i).aggregate(Max('id'))
	     b=answers.objects.get(id=a['id__max'])
             b.answer = request.POST[i]
             b.save()
         except:
             apple=""
#    for i in request.session['mcq'][1]:
#        if str(i.pk) in request.POST:
#            if i.answer == request.POST[str(i.pk)]:
#                count = count + 1
#      #          request.session['counter'][1] = request.session['counter'][1] + 1
#            ans2.append(request.POST[str(i.pk)])
#        else:
#            ans2.append(0)
    #return HttpResponse( request.session['mcq'])
    try:
        c = list(Questiondetails.objects.filter(category=3))
        random.shuffle(c)
        mcq = c[:1]
        for i in mcq:
            v=Questiondetails.objects.get(id=i.id)
            b=answers(memberid=uid,qid=v,answer=0)
            b.save()	
#     request.session['mcq'][0] = copy.deepcopy(a[:1])
    except Questiondetails.DoesNotExist:
        raise Http404
	
#	return HttpResponse(myanswers)
    return render(request,'mcqportal/pg3.html',{'mcq':mcq,'user':request.session['name']})

def pg4(request):
    if 'uid' not in request.session :
        return render(request,'mcqportal/login.html')
    if  'pg4session' not in request.session:
	return chksession(request)

    uid=request.session['uid']
    for i in request.POST:
        #		myanswers+="qid-"
#		myanswers+=i
#		myanswers+="the answer-"
#		myanswers+=request.POST[i]
         try:
             a=answers.objects.filter(qid=i).aggregate(Max('id'))
	     b=answers.objects.get(id=a['id__max'])
             b.answer = request.POST[i]
             b.save()
         except:
             apple=""


#    global ans3
#    global mcq3
#    try:
#        a = list(Questiondetails.objects.all())
#        random.shuffle(a)
#        request.session['mcq'][3] = copy.deepcopy(a[:1])
#        c = Context({"mcq" : request.session['mcq'][3]})
#    except Questiondetails.DoesNotExist:
#        raise Http404
#    for i in request.session['mcq'][2]:
#        if str(i.pk) in request.POST:
#            if i.answer == request.POST[str(i.pk)]:
#                count = count + 1
# ##               request.session['counter'][2] = request.session['counter'][2] + 1
#            ans3.append(request.POST[str(i.pk)])
#        else:
#            ans3.append(0)
#    lis = request.session['counter']
#    lis.append(count)
#    request.session['counter'] = copy.deepcopy(lis)
#    request.session['counter'].append(count)
#    return render(request,'mcqportal/pg4.html',{'mcq':request.session['mcq'][3], 'b':"Reasoning"})
    try:
        c = list(Questiondetails.objects.filter(category=4))
        random.shuffle(c)
        mcq = c[:1]
        for i in mcq:
            v=Questiondetails.objects.get(id=i.id)
#            w=Members.objects.get(id=i.id)
            b=answers(memberid=uid,qid=v,answer=0)
            b.save()	
#     request.session['mcq'][0] = copy.deepcopy(a[:1])
    except Questiondetails.DoesNotExist:
        raise Http404
	
#	return HttpResponse(myanswers)

synapz/WebApp/mcq-latest/mcqportal/templates/mcqportal/bkp_index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Synapz</title>
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/bootstrap.css' %}">
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/style1.css' %}" >
</head>
<body>
<div class="container">

		<form method="post" action="p1_submit"> {% csrf_token %}
		<input id="submit" type="submit" name="submit" value="submit"></form>

</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="./js/bootstrap.min.js"></script>
</body>
</html>	

synapz/WebApp/mcq-latest/mcqportal/templates/mcqportal/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <title>Synapz</title>
    <link href="{% static 'mcqportal/bootstrap.css' %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 20px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 30px 0;
        
      }
      .jumbotron .btn {
        padding: 14px 24px;
        font-size: 21px;
      }
      /* Supporting marketing content */
      #instructions {
 	border:2px solid #5eac1a;
      }
      #instructions td {
      	border-right: 2px dotted #5eac1a;
	padding: 5px;
      }
     #heading {
	color:#5eac1a;
	font-size:20px;
     }
     #intro {
	text-align: center;
	padding-bottom: 20px;
     }
     .footer {
 	text-align: center;
     }
     #index {
	padding-top:20px;
	}
     .pull-right {
	float:right;
	padding-right:20px;
     }
     #first {
	width: 50%;
     }
    </style>
  </head>

  <body>



    <div class="container-narrow">

      <div class="masthead">
	<ul class="nav nav-pills pull-right">
	  <li><a href="#">Logged in as {{ user }} </a></li>
	  <li><a href="#">Logout </a></li>
	</ul>
        <h3 class="muted">Synapz</h3>
      </div>
   
      <hr>

      <div class="jumbotron">
        <div id="intro"><h2>Welcome to Synapz's adaptive learning platfrom through MCQ's</h2></div>
        <table >
	    
  		<tr><td><p id="heading"><b>Instructions : </b></p></td></tr>
		<tr id="instructions"><td id="first">
			<ul>
			<li>Total number of sections : <b> 4 </b></li>
			<li>Total number of questions per section : <b> 15 </b></li>
			<li>Time alloted per section : <b>30 minutes.</b></li>
			<li>Each question carry <b>1</b> mark, <b>no negative marks.</b></li>
			</ul>
		</td>
		<td>
			<ul>
			<li>Click the 'Submit Test' button given in the bottom of this page to Submit your answers.</li>
			<li>Test will be submitted automatically if the time expired.</li>
			<li>Don't refresh the page.</li>
			</ul>
		</td>
	    </tr>	
	</table>
	<form id="index" method="post" action="{% url 'mcqportal:pg1' %}">
		{% csrf_token %}
		<center><input type="submit" id="btnSubmit" class="btn btn-primary" name="submit" value="Start Test"></center>
	</form>
     <hr>
      
      <div class="footer">
        <p>Synapz Company 2013</p>
      </div>

    </div> <!-- /container -->
</div>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="./bootstrap.min.js"></script>

<script type = "text/javascript" >
        function preventBack(){window.history.forward();}
                setTimeout("preventBack()", 0);
                        window.onunload=function(){null};
                    </script>

            </body>
        
        </html>

synapz/WebApp/mcq-latest/mcqportal/templates/mcqportal/pg1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Synapz</title>
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/bootstrap.css' %}">
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/style1.css' %}" >
<style type="text/css">
	body {
			    padding-bottom: 40px;
			    	    padding-top: 60px;
				    	}
	
	.sidebar-nav-fixed {
			    padding: 9px 0;
				     	    position:fixed;
						     	    left:20px;
								 	    top:60px;
											    width:250px;
												  	}
	
	.row-fluid > .span-fixed-sidebar {
			    margin-left: 290px;
			    	}
	.pull-right {
				padding-right: 20px;
					}
	</style>
	<script type="text/javascript">
	window.onload=function(){}
	</script>
</head>
<body>

<script type = "text/javascript" >
        function preventBack(){window.history.forward();}
                setTimeout("preventBack()", 0);
                        window.onunload=function(){null};
                    </script>


  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">

	 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	  	<span class="icon-bar"></span>
		 <span class="icon-bar"></span>
	             <span class="icon-bar"></span>
		     </a>
		     <a class="brand" href="#">Synapz</a>
	 <div class="nav-collapse">
	 <p class="navbar-text pull-right"><a href="/mcqportal/logout"> Logout </a></p>
	 <p class="navbar-text pull-right">Logged in as </p>
	 </div>

	 </div>
	 </div>
</div>


<script>
var Timer;
var TotalSeconds;
function CreateTimer(Time) {
Timer = document.getElementById("timer");
TotalSeconds = Time;
UpdateTimer()
window.setTimeout("Tick()", 1000);
}
function Tick() {
if (TotalSeconds <= 0) {
var btn=document.getElementById("btnSubmit");
btn.click(); 
return;
}
TotalSeconds -= 1;
UpdateTimer()
window.setTimeout("Tick()", 1000);
}
function UpdateTimer() {
var Seconds = TotalSeconds;
var Hours = Math.floor(Seconds / 3600);
Seconds -= Hours * (3600);
var Minutes = Math.floor(Seconds / 60);
Seconds -= Minutes * (60);
var TimeStr = (LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds));
Timer.innerHTML = TimeStr;
}
function LeadingZero(Time) {
return (Time < 10) ? "0" + Time : + Time;
}
</script>

<div class="container">

		<form method="post" action="{% url 'mcqportal:pg2' %}">
		{% csrf_token %}
<!--		<input id="submit" type="submit" name="submit" value="submit"></form>  -->

		<div id="section">
		<table><tr><td>Programing</td></tr>
		<tr class="table2"><td>General Aptitude </td></tr>
		<tr><td>Reasoning        </td></tr>
		<tr><td>Algorithms       </td></tr>
		</table>
		</div>
		<div id="exam">
		<table class="table2">
		<tr><td id="timer"><b>Timer</b></td><td id="section-name"><b>Programming</p></td></tr></table>
		{% for quest in mcq %}
			<table class="table table-hover">
			<tr><td colspan="2"><b>{{ quest.question }}</b></td></tr>
            <tr><table class="table1"><tr><td><input type="radio" name="{{ quest.id }}" value="1"> A . {{ quest.optiona }}</td>
			<td><input type="radio" name="{{ quest.id }}" value="3"> C . {{ quest.optionc }}</td></tr>
			<tr><td><input type="radio" name="{{ quest.id }}" value="2"> B . {{ quest.optionb }}</td>
			<td><input type="radio" name="{{ quest.id }}" value="4"> D . {{ quest.optiond }}</td></tr></table></tr>
			</table>
		{% endfor %}
        <input type="hidden" name="page" value="pg1"/>
		
{% comment %}	{% for i in mcq %}        
			{% b.append(i.id) %}   
		{% endfor %}
{% endcomment %}          
		<center><input type="submit" id="btnSubmit" class="btn btn-primary" name="submit" value="submit"></center>          
		
</form>
		<center><footer>Synapz Company 2013</footer></center>
</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script>
window.onload = CreateTimer(30*60);
</script>

</body>
</html>	

synapz/WebApp/mcq-latest/mcqportal/templates/mcqportal/pg2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Synapz</title>
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/bootstrap.css' %}">
<link rel="stylesheet" type ="text/css" href="{% static 'mcqportal/style1.css' %}" >
<style type="text/css">
	body {
			    padding-bottom: 40px;
			    	    padding-top: 60px;
				    	}
	
	.sidebar-nav-fixed {
			    padding: 9px 0;
				     	    position:fixed;
						     	    left:20px;
								 	    top:60px;
											    width:250px;
												  	}
	
	.row-fluid > .span-fixed-sidebar {
			    margin-left: 290px;
			    	}
	.pull-right {
				padding-right: 20px;
					}
	</style>
	<script type="text/javascript">
	window.onload=function(){}
	</script>
</head>
<body>

<script type = "text/javascript" >
        function preventBack(){window.history.forward();}
                setTimeout("preventBack()", 0);
                        window.onunload=function(){null};
                    </script>


  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">

	 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	  	<span class="icon-bar"></span>
		 <span class="icon-bar"></span>
	             <span class="icon-bar"></span>
		     </a>
		     <a class="brand" href="#">Synapz</a>
	 <div class="nav-collapse">
	 <p class="navbar-text pull-right"><a href="/mcqportal/logout"> Logout </a></p>
	 <p class="navbar-text pull-right">Logged in as {{ user }}</p>
	 </div>

	 </div>
	 </div>
</div>


<script>
var Timer;
var TotalSeconds;
function CreateTimer(Time) {
Timer = document.getElementById("timer");
TotalSeconds = Time;
UpdateTimer()
window.setTimeout("Tick()", 1000);
}
function Tick() {
if (TotalSeconds <= 0) {
var btn=document.getElementById("btnSubmit");
btn.click(); 
return;
}
TotalSeconds -= 1;
UpdateTimer()
window.setTimeout("Tick()", 1000);
}
function UpdateTimer() {
var Seconds = TotalSeconds;
var Hours = Math.floor(Seconds / 3600);
Seconds -= Hours * (3600);
var Minutes = Math.floor(Seconds / 60);
Seconds -= Minutes * (60);
var TimeStr = (LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds));
Timer.innerHTML = TimeStr;
}
function LeadingZero(Time) {
return (Time < 10) ? "0" + Time : + Time;
}
</script>

<div class="container">

		<form method="post" action="{% url 'mcqportal:pg3' %}">
		{% csrf_token %}
<!--		<input id="submit" type="submit" name="submit" value="submit"></form>  -->

		<div id="section">
		<table><tr><td>Programing</td></tr>
		<tr class="table2"><td>General Aptitude </td></tr>
		<tr><td>Reasoning        </td></tr>
		<tr><td>Algorithms       </td></tr>
		</table>
		</div>
		<div id="exam">
		<table class="table2">
		<tr><td id="timer"><b>Timer</b></td><td id="section-name"><b>Aptitude</p></td></tr></table>
		{% for quest in mcq %}
			<table class="table table-hover">
			<tr><td colspan="2"><b>{{ quest.question }}</b></td></tr>
            <tr><table class="table1"><tr><td><input type="radio" name="{{ quest.id }}" value="1"> A . {{ quest.optiona }}</td>
			<td><input type="radio" name="{{ quest.id }}" value="3"> C . {{ quest.optionc }}</td></tr>
			<tr><td><input type="radio" name="{{ quest.id }}" value="2"> B . {{ quest.optionb }}</td>
			<td><input type="radio" name="{{ quest.id }}" value="4"> D . {{ quest.optiond }}</td></tr></table></tr>
			</table>
		{% endfor %}
        <input type="hidden" name="page" value="pg2"/>
		
{% comment %}	{% for i in mcq %}        
			{% b.append(i.id) %}   
		{% endfor %}
{% endcomment %}          
		<center><input type="submit" id="btnSubmit" class="btn btn-primary" name="submit" value="submit"></center>          				
</form>
		<center><footer>Synapz Company 2013</footer></center>
</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script>
window.onload = CreateTimer(30*60);
</script>

</body>
</html>	

synapz/WebApp/mcq-latest/mcqportal/templates/mcqportal/pg5old.html
{% load staticfiles %}

<p> Your answer : 0 ,means not attempted </p>
</br>
</br>

{% for i in mcq %}

<p> Questionid {{i.qid}} </p>
<p> Correct answer: {{i.qid.answer}} </p>
<p> Your answer : {{i.answer}} </p>

{% endfor %}